### PR TITLE
Added ability to provide external routing config for extra custom routes

### PR DESCRIPTION
**Pull request by aantono**
This PR provides ability to externally configure additional routing configuration to be able to add custom route handlers in addition to the default ones.

### CODE REVIEW

**Review by matlockx — COMMENTED** [review]
Lgtm.
I see the point following the links in your issue, but honestly I think it's a bit sad that client implementations for an open server format now forces other implementations to have the same endpoints for healthchecks and stuff. But maybe I'm seeing it wrong and we should have provided all the endpoints in the first place ....

**Comment by aantono** [comment]
@matlockx any chance this can get merged, if there are no outstanding issues?  I'm waiting for this PR to enable the functionality to proceed with integration with the Zipkin Chrome Extension, so would be nice to have it... 😉

**Comment by matlockx** [comment]
Thanks

**Comment by aantono** [comment]
Thank you!!!

**Pull request merged**
